### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by CyberMew** [danitetus/pushover-js#4]
For the user tokens, currently it only accept 1 entry.  Is it possible to accept an array of entries? I have to send it to different people, and group does not work for me because the notifications will disappear for all others, once the first person to ack the message.

**Comment by d4nicoder** [comment]
It would not be a good idea to implement within the class because if we processed several users at the same time, if one fails, we cannot determine which one has failed. We would have to store the request responses and return them in an array, but it would be confusing and difficult to debug. Because what should be the behavior? Should we throw an exception when a single delivery fails? Or when all of them fail? Should we stop when one fails? Or continue? It would not be consistent behavior.

It is better to preserve the atomicity of each message and handle the mass sending by instantiating as many classes as messages you need to send.

For example:

```typescript
for (const userId of usersList) {
  const message = new Pushover(userId, token)
  p.send(`Message to user ${userId}`, 'Message content')
    .then((res) => {
      console.log(`Message to user ${userId} successfully sent`)
    })
    .catch((error) => {
      console.error(`Message to user ${userId} failed`)
    })

}
```

**Comment by d4nicoder** [comment]
According to the Pushover API documentation, you can group messages to multiple users, passing a comma-separated list of users as an argument

> Alternatively, a message may be sent to multiple users in one request by specifying a comma-separated list (with no spaces) of user keys as the user parameter. These requests are currently limited to 50 users in a single request.
([API documentation](https://pushover.net/api#identifiers))

Therefore, you can pass that list of users as an argument to wrap all the messages in a single request.

**Comment by CyberMew** [comment]
Awesome find, didn’t see that. Having Pushover handling it internally would be best. Thanks for that! I also appreciate your detailed response!
